apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - /hyperkube
    - controller-manager
    - --master=http://172.16.7.39:8080
    - --leader-elect=true
    image: gcr.io/google_containers/hyperkube:v1.5.7
    name: kube-controller-manager
  hostNetwork: true
